### PR TITLE
Modularized SUEPCoffea.py, Plotting notebook improved

### PR DESCRIPTION
**Pull request by lucalavezzo**

### CODE REVIEW

**Comment by chrispap95** [comment]
Hi Luca,

Can you briefly say what's the bug with the current implementation of the cluster method? The changes are too many to keep track of. 

(I am interested because I am running the code for the muon trigger as well - see `muon_triggers` branch)

**Comment by lucalavezzo** [comment]
Hi Christos,
So [this line](https://github.com/SUEPPhysics/SUEPCoffea_dask/blob/de0e176eef71f354deee4be73728b519955b5967/workflows/SUEP_coffea.py#L485) has oneIRMtrackCut, which is defined inside and for ISR Removal method. instead of the correct oneISRtrackCut.
Also, [this line](https://github.com/SUEPPhysics/SUEPCoffea_dask/blob/de0e176eef71f354deee4be73728b519955b5967/workflows/SUEP_coffea.py#L492) was the main issue, ISR_tracks_b as used here is only defined inside ISR Removal Method; the correct line should be:
`ISR_tracks_b_CL = ISR_tracks_b_CL[oneISRtrackCut]`
As you can see, both of these issues were due to the different methods having overlaps in some of the variables, which is why we moved everything inside their own function.
Let me know if there are other issues with this.
Thanks!
Luca

**Comment by chrispap95** [comment]
I see, both slipped my attention. Thanks!

**Comment by lucalavezzo** [comment]
No, my bad, I should've commented which bugs were fixed!

**Pull request merged**
